<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>janilla-website-template-frontend</artifactId>
	<parent>
		<groupId>com.janilla</groupId>
		<artifactId>janilla-website-template</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<build>
		<plugins>
			<plugin>
				<groupId>io.github.download-maven-plugin</groupId>
				<artifactId>download-maven-plugin</artifactId>
				<version>2.0.0</version>
				<executions>
					<execution>
						<id>install-geist-font</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
						<configuration>
							<url>https://github.com/vercel/geist-font/releases/download/1.6.0/geist-font-1.6.0.zip</url>
							<unpack>false</unpack>
							<outputDirectory>${project.build.directory}/classes/com/janilla/websitetemplate/frontend</outputDirectory>
							<sha256>784a8ea7d16e1dd71ceaad52f6f92d557ae58fd76c292b9f6d370085df936f53</sha256>
						</configuration>
					</execution>
					<execution>
						<id>install-lucide-icons</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
						<configuration>
							<url>https://github.com/lucide-icons/lucide/releases/download/0.562.0/lucide-icons-0.562.0.zip</url>
							<unpack>false</unpack>
							<outputDirectory>${project.build.directory}/classes/com/janilla/websitetemplate/frontend</outputDirectory>
							<sha256>bf4db856555194a2d8b855fc72169892f28f5bcab10222db2cada11e8966581a</sha256>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<configuration>
					<executable>java</executable>
					<arguments>
						<argument>-p</argument>
						<modulepath/>
						<argument>-m</argument>
						<argument>com.janilla.websitetemplate.frontend/com.janilla.websitetemplate.frontend.WebsiteTemplateFrontend</argument>
					</arguments>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>