website-template.api.cors.headers=Content-Type
website-template.api.cors.origin=https://localhost:8443
website-template.api.url=https://localhost:8444/api
website-template.backend.server.port=8444
website-template.database.file=~/janilla/sample-data/website-template.database
website-template.jwt.key=secretkey
website-template.live-demo=false
website-template.upload.directory=~/janilla/sample-data/website-template-upload
