website-template.api.url=https://localhost:8444/api
website-template.frontend.server.keystore.path=~/janilla/mykeystore
website-template.frontend.server.keystore.password=password
website-template.frontend.server.port=8443
website-template.jwt.cookie=website-token
website-template.jwt.key=secretkey
website-template.title=Janilla Website Template
